## numpy tutorial: iterate numpy array using nditer | numpy nditer

In [1]:
import numpy as np

In [2]:
#creat an array
# here i use 'arange' function and have 12 elements, and reshape into 3 by 4
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# i got this numpy array which is two dimensional array

In [3]:
# simple way of iterating through this array is to run for loop on it
for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [4]:
# if you are interested itering over each of these elements one by one then u can introduce one more
# for loop
for row in a:
    for cell in row:
        print(cell)
        # that will print all individual elements
 #for this way u need to write two for loops                   

0
1
2
3
4
5
6
7
8
9
10
11


In [5]:
#now if you just want to flattern this array into a list simply called flatten()
# write one single for loop be done with it
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


### numpy.nditer

In [7]:
# numpy offers a function called 'nditer' allows to do more suffosticated of iteration
# for example:
for x in np.nditer(a,order='c'):
    print(x)
#the first arguement is array itself and 2nd is order

0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
# itfact its has same effect as flatten
# essentially u r going by row by row printing values in each of theses columns

In [8]:
#lets see if u r a fortran programmer and u want to go column by column instead of row by row
# instead of printing 0,1,2,3,4.....you want to print 0,4,8,1....then u just change your order to be
for x in np.nditer(a,order='F'):
    print(x)
    #then u will see now u r printing order into fortran order
    # thats the benefit of nditer it allows u to iteration in vareity of ways

0
4
8
1
5
9
2
6
10
3
7
11


In [9]:
# if i want to print entire column, basically print entire column on each iteration
# you do this by supplying flags and here the value u provide is 'external_loop' when u do that each 
#  each iteration is printing iterating entire column
for x in np.nditer(a,order='F',flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [10]:
# lets u r iterating an array u have to modify elements using that perticular flag
for x in np.nditer(a,op_flags=['readwrite']):
    #the covention that u have to follow is...
    x[...]=x*x# i want to create square of these elements in these array & i want to modify the
    #  original array


In [11]:
#i will print array
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
# you will notice that my original is modified, each of these elemnts are the suare of original array

In [12]:
# now how do u iterate through two numpy arrays simultaneously
# 2 arrays at the same time
#lets crate another array

In [13]:
#this time going to create array with different dimension
b = np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [14]:
# i want to iterate these two arrays a,b simultaneously
for x,y in np.nditer([a,b]):
    print(x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11


In [15]:
# now u can iterate through two arrays simultaneously

In [ ]:
#general Broadcasting rules:
when operating on two arrays. Numpy compares their shapes element-wise.it starts with the trailing
dimensions and works its way forward. Two dimensions are compatible when,
1.they are equal, or
2.one of them is 1