# numpy tutorial - basic array operations

In [2]:
import numpy as np
a = np.array([5,6,9])               

In [3]:
a[0]

5

In [4]:
a[1]

6

In [8]:
a = np.array([[1,2],[3,4],[5,6]])
a.ndim                             #two Dimensional array
# we have this property called ndim that we can use to print dimensions.

2

In [9]:
a = np.array([[[1,2],[3,4],[5,6]]])
a.ndim                               # three Dimensional array

3

In [11]:
a = np.array([5,6,9])
a.ndim                         #one Dimensional array

1

In [13]:
a = np.array([[1,2],[3,4],[5,6]])
a.ndim       

2

In [14]:
a.itemsize           #it will print the byte size of each of these elements in the array
# for integer elements it will print each element = 4 bytes

4

In [16]:
a.dtype      #this is the current datatype of an present array

dtype('int32')

In [20]:
# same array with different datatype
a = np.array([[1,2],[3,4],[5,6]], dtype=np.float64)

In [22]:
a.itemsize # with float it occupies each element as a 8

8

In [23]:
a          # this now a float dtype

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [24]:
#another important property is that an array has is 'size'
a.size
#size appear total number elements in an arary

6

In [25]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [26]:
#shape represents the information on dimentions short of like width and height, '3 rows','2 columns'
a.shape

(3, 2)

In [28]:
#creating an array with complex numbers
a = np.array([[1,2],[3,4],[5,6]], dtype=np.complex_)

In [29]:
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [30]:
#initializing array with zeros
np.zeros( (3,4) )          # it initialize 3 rows and 4 columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
np.ones( (3,4) ) #initialize all elements as a one in array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
# similarly we have range function in python using for a list
l = range(5)
l

range(0, 5)

In [ ]:
# it creats list of numbers 0 to 4

In [35]:
l[0]

0

In [36]:
l[1]

1

In [34]:
#numpy as have similar fuction called 'arange'
np.arange(1,5)

array([1, 2, 3, 4])

In [37]:
# step of 2
# np.arange(start,stop(end),step of 2 or more(difference))
np.arange(1,5,2)

array([1, 3])

In [38]:
# you can also use 'linspace'
#in linspace you will specify start num=1, stop num=5,in b/w these two numbers i want to generate 10
#10 will generate numbers b/w 1 and 5 which are linearly spaced.
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
#we got nice range of 1 and 5 and these numbers are linearly spaced

In [39]:
# we will do the same thing with 5
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [ ]:
#they are space by num 1

In [40]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [ ]:
#this is big use to create the linear sequence of numbers

In [41]:
# you can also reshape an arrays with the reshape function
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
a.shape

(3, 2)

In [44]:
a.reshape(2,3)# reshaped the above array dim

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [46]:
# you can also use ravel() function to flattern your array
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [ ]:
# this flatternate to make it one dimensional

In [47]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# if you print a after ravel it will print original one
# bcoz a.ravel() function does not touch an original array it will return a new array
#it does not going to alter our original array

### lets look at the some mathematical functions numpy array covers

In [48]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
a.min()

1

In [51]:
a.max()

6

In [52]:
a.mean()

3.5

In [53]:
a.std()

1.707825127659933

In [54]:
a.sum() # it going to sum all the numbers together

21

### there is concept of axis in numpy array

In [55]:
#axis means dimension
#axis=0 and axis=1
#my axis=0 will be my columns and axis=1 will be rows
a.sum(axis=0)

array([ 9, 12])

In [ ]:
#if i print axis=0
# it is added the numbers together in each column
# sum of elements in columns together

In [56]:
a.sum(axis=1)

array([ 3,  7, 11])

In [ ]:
#if i print axis=1
# it is added the numbers together in each row
#sum of elements in rows together


In [ ]:
#thats what the axis means here

### you can also do a sqrt 

In [57]:
#if you can do a.sqrt() 
a.sqrt()

AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'

In [59]:
#### sqrt is not a function of individual array element its a genric func 
# so you have to do
np.sqrt(a)
#bcoz np is your numpy module so its gonna compute sqrt of each these numbers
#for example 4 sqrt you know is a 2

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [60]:
#you can also do standard deviation
np.std(a) # or a.std()

1.707825127659933

In [62]:
# i have 2 dimensional array here
a = np.array([[1,2],[3,4]])

In [63]:
b = np.array([[5,6],[7,8]])

In [64]:
a

array([[1, 2],
       [3, 4]])

In [65]:
b

array([[5, 6],
       [7, 8]])

In [66]:
#numpy array supports basic operations such as if you want to add together using + operator
# this something u can't do with python native list so its very convinient
a+b


array([[ 6,  8],
       [10, 12]])

In [67]:
a-b

array([[-4, -4],
       [-4, -4]])

In [68]:
a*b

array([[ 5, 12],
       [21, 32]])

In [69]:
a/b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [70]:
#you will also do a matrix product
a.dot(b)

array([[19, 22],
       [43, 50]])

In [71]:
a.dot(a)

array([[ 7, 10],
       [15, 22]])

In [ ]:
#this will do the matrix product of these 2 of individual martices

### That was all about numpy array