# numpy array vs python list

Numpy's most useful feature is n dimensional array object(a.k.a ndaray)

In [3]:
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
a[0]

1

In [5]:
a[1]

2

In [ ]:
question is i already have a list then whats so special about numpy array?
there are several benefits of using Numpy Array, there are 3 main benefits of numpy array over a
python list,
(1) Less Memory
(2) Fast
(3) Convinient

In [ ]:
we will go with one on one benefit

In [15]:
import time
import sys

In [16]:
l = range(1000)
print(sys.getsizeof(5)*len(l))                  # 1st benefit is Less Memory
array = np.arange(1000)
print(array.size*array.itemsize)
#numpy array has less usage of memory compare to plain python list


28000
4000


In [ ]:
going to the another benefit - 'Fast','convinient'

In [ ]:
now i am showing you numpy array is fast and convinient compared to native python list.

In [21]:
SIZE = 1000000

l1 = range(SIZE)
l2 = range(SIZE)

a1 = np.arange(SIZE)
a2 = np.arange(SIZE)

#PYTHON LIST
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("python list took: ",(time.time()-start)*1000)

#Numpy Array
start = time.time()
result = a1 + a2
print("numpy took: ",(time.time()-start)*1000)

python list took:  151.60584449768066
numpy took:  24.02806282043457


In [ ]:
the output u can see that how fast numpy than python list the time difference that we can measure b/w 
the numpy and python .

In [ ]:
im going to create two numpy array

In [22]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

In [23]:
a1+a2

array([5, 7, 9])

In [26]:
a2-a1

array([3, 3, 3])

In [27]:
a1*a2

array([ 4, 10, 18])

In [28]:
a1/a2

array([0.25, 0.4 , 0.5 ])

In [ ]:
#we do all these above operations#