# Topics:

### Indexing and slicing:

In [1]:
import numpy as np

In [2]:
#when we have normal python list 
n = [6,7,8]
#we do slicing like this
n[0:2]  # when u do 0 to 2 - what it will do is it will print 6,7 it will not cover 8.
# 0:2 it will cover upto 1 

[6, 7]

In [3]:
n[-1]
#it also supports -1. -1 means it starts from ending from last element

8

In [4]:
#numpy array supports similar kind of slicing
# here im going to create numpy array, here im initialiging same elements.
a = np.array([6,7,8])
#if u do 
a[0:2]
#here u will see the same as above normal python list slicing

array([6, 7])

In [5]:
#it also supports reverse index -1
a[-1]
#it is kinda similar to normal python list slicing that we can use for numpy array

8

In [7]:
#lets go through multi-dimensional array
a=np.array([[6,7,8],[1,2,3],[9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [8]:
a[1,2]

3

In [9]:
a[0:2,2]

array([8, 3])

In [21]:
a[-1]

array([9, 3, 2])

In [22]:
a[-1,0:2]

array([9, 3])

In [24]:
a[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [25]:
a[1:3]

array([[1, 2, 3],
       [9, 3, 2]])

### iterating through arrays:

In [26]:
import numpy as np

In [27]:
a=np.array([[6,7,8],[1,2,3],[9,3,2]])
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [30]:
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [31]:
#numpy has a method called flat
for cell in a.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


In [32]:
# whats the flat method is doing is,its flatterning a single dimensional array,
#now it can iterate through entire array

### Stacking together two arrays

In [2]:
import numpy as np
a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)

In [3]:
#first let we have two arrays
#a=np.arrange(6).reshape(3,2)
#what i'm doing is im initializing numbers 0 to 5 and reshaping it by 3/2
#and im having 'b'
#b=np.arrange(6,12).reshape(3,2)

In [4]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [5]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [6]:
#so u have lets say 2 dimensional array


In [6]:
#now if u want to  vertically stack them together ,numpy supports that
np.vstack(a,b)

TypeError: _vhstack_dispatcher() takes 1 positional argument but 2 were given

In [7]:
#i have a error syntax, actually the argument is tuple actually ..
np.vstack((a,b))
#vertically stacking
#the box represent up & down

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [8]:
#horizontally stacking
np.hstack((a,b))
#the box represent side-by-side

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [9]:
#horizontal splits
#now again im initializing new array
a=np.arange(30).reshape(2,15)
#this array having 2 rows 15 columns

In [10]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [11]:
np.hsplit(a,3)
#by using this it split it into three different arrays

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [12]:
#now its kind of hard to visualize, so now what im going to is im going to store the result into a 
# variable which is a list and just print those things one by one
result = np.hsplit(a,3)

In [13]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [14]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [15]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [17]:
#you can see that i kinda vertically sliced these big array into 3 different  arrays by doing
# hsplit (a,3) here 3 means divided into 3 equal sized

In [16]:
result = np.vsplit(a,2) # in vertical i have only 2 rows

In [17]:
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [18]:
result[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [23]:
# i can make only 2 divisions out of it

### Indexing with boolean arrays

In [20]:
#its kind of non interior
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
#here it stores the results of this above expression
# here 0 is not greater than 4 so its expression is false
# 11 is greater than 4 so its bool expression is true
#now pritty good i got 2 arrays 1 is numbers and another one is boolen


In [22]:
a[b] #a is array and array of its index b is array itself 

array([ 5,  6,  7,  8,  9, 10, 11])

In [23]:
# this kinda original one from 5 to 11 it is true so its given all true elements 
#this is a cool way of extracting all the elements which are greater than four from your original 
# array
# this is also useful that u want to replace those elements with certain numbers
#### for example i can say
a[b]=-1

In [24]:
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [25]:
# any element that greater than 4 you wanted to replace with -1 and thats what it did
# this could be really powerfull based on what applications you write

In [ ]:
#numpy arrays are very fast and memory efficient

## That is all about array functions